[package]
name = "devpng"
version = "0.1.0"
authors = ["TimeEngineer <chenpascal241096@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
